### ISSUE TITLE
Database structure for sys_file_reference

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-FileAbstractionLayer#9]
https://docs.typo3.org/typo3cms/FileAbstractionLayerReference/Developers/Architecture/DatabaseStructure/Index.html

there are some fields at the bottom of the listing:

```
 deleted          tinyint(4) DEFAULT '0' NOT NULL,
   hidden           tinyint(4) DEFAULT '0' NOT NULL,
   starttime        int(11) DEFAULT '0' NOT NULL,
   endtime          int(11) DEFAULT '0' NOT NULL,
```

**Comment by fsuter** [comment]
I plan to remove the table definitions entirely. I have they have no added value, anyone can look up the structure in their favorite SQL client if they need to, and they don't bring any additional understanding about how FAL works.

**Comment by tmotyl** [comment]
it would be great if we have a diagram showing table relations instead of the sql listing.
Inluding information about which table represents what. Recently I found out the the sys_file 'metadata' column is always 0, and the relation is stored in the sys_file_metedata 'file' column

**Comment by fsuter** [comment]
Yes, that would be far more useful.

**Comment by Chrissitopher** [comment]
I like your idea. MediaWiki has something like that [here](https://upload.wikimedia.org/wikipedia/commons/f/f7/MediaWiki_1.24.1_database_schema.svg). 

For us, it would be great, to have such a diagram created more or less automatically, without the need to manually draw something. [This thread](http://stackoverflow.com/questions/2488/auto-generate-database-diagram-mysql) sounds like MySQL workbench could do that...

**Comment by tmotyl** [comment]
@Chrissitopher it's nice, but it misses the relation information

**Comment by Chrissitopher** [comment]
You can add the relationship information like so: After you once went through the Reverse Engineer menu (which is pretty self-explanatory), you have the diagram with all the tables and all the columns (they call it "EER Diagram"). 
Then you can create relations just by clicking the fitting relations icon from the menu (`1:1`, `1:n`, `n:1` or `n:m`) and then clicking the tables you want to connect. 

Give it a try!

**Comment by ohader** [comment]
Issue can be closed I guess
